[package]
name = "lambda-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
include-wasm-rs = "0.2.0"
wasmtime = "25.0"

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

# Use for benching web
wasmer = "4.2"

[[bench]]
name = "benches"
harness = false