[package]
name = "lambda-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "benches"
harness = false